data:
    raw:
        rnaseq_expression:
            -
                file: /data/datasets/raw/rnaseq_expression/HMCL_ensembl74_Counts.txt
                description: description place holder

        gene_ontology:
            -
                file: /data/datasets/raw/gene_ontology/ensembl_go_mapping.tab
                description: description
        exome_vcfs:
            -
                path: /data/datasets/raw/exome_variants/
                description: Variants in each cell line
    filtered:
        rnaseq_expression:
            -
                file: /data/datasets/filtered/rnaseq_expression/HMCL_ensembl74_Counts_normalized.csv
                description:
            -
                file: /data/datasets/filtered/rnaseq_expression/HMCL_ensembl74_Counts_normalized.csv
                description:


